export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
export const RESET_FORM_DATA = 'RESET_FORM_DATA';
export const SUBMIT_FORM_DATA = 'SUBMIT_FORM_DATA';
export const HANDLE_SUBMIT_SUCCESS = 'HANDLE_SUBMIT_SUCCESS';
export const HANDLE_SUBMIT_ERROR = 'HANDLE_SUBMIT_ERROR';
export const VALIDATE_FORM_DATA = 'VALIDATE_FORM_DATA';
