export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
export const RESET_FORM_DATA = 'RESET_FORM_DATA';
export const SUBMIT_FORM_DATA = 'SUBMIT_FORM_DATA';
export const HANDLE_SUBMIT_SUCESS = 'HANDLE_SUBMIT_SUCESS';
export const HANDLE_SUBMIT_ERROR = 'HANDLE_SUBMIT_ERROR';
